name: testflutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.11
  google_generative_ai: ^0.0.1-dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  connectivity_plus: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/logoup.jpg
